name: Build & Deploy
on: [push]

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, '[skip test]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses:  actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Run tests
        run: |
          yarn
          yarn lint
  build-push-container:
    if: ${{ !contains(github.event.head_commit.message, '[skip app]') }}
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses:  actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Build & deploy
        run: bash ./.github/workflows/build.sh
