name: Build & Deploy
on: [push]

jobs:
  build_app:
    name: Build app
    if: ${{ !contains(github.event.head_commit.message, 'skip app') }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build app
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: bash ./scripts/build_app.sh ${{ github.job }}